# parser.dart - a fork of PetiteParser
name: parser
version: 1.0.0
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
description: Fork of PetiteParser, the dynamic parser combinator framework.
homepage: https://github.com/DirectMyFile/parser.dart
environment:
  sdk: '>=1.5.0'
dev_dependencies:
  browser: '>=0.9.0 <0.11.0'
  junitconfiguration: '>=1.0.0 <2.0.0'
  matcher: '>=0.9.0 <0.11.0'
  unittest: '>=0.9.0 <0.12.0'
